name: xicom_test_rohit

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  dio: ^5.6.0
  form_validator: ^2.1.1
  image_picker: ^1.1.2
  flutter_animate: ^4.5.0
  flutter_easyloading: ^3.0.5
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
